version: "2"

services:
  backend:
    container_name: backend
    build: ./server
    restart: always
    volumes:
      - "./server:/Backend"
    ports:
      - "5000:5000"

  client:
    container_name: client
    build: ./client
    stdin_open: true
    restart: always
    volumes:
      - "./client:/App"
    ports:
      - "8000:8000"

  web-server:
    container_name: web-server
    build: ./web-server
    restart: always
    volumes:
      - ./web-server/conf.d:/etc/nginx/conf.d
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - client

  cache-lru:
    container_name: cache-lru
    image: redis
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - "./data/redis-lru/redis-data:/var/lib/redis"
      - "./data/redis-lru/redis.conf:/usr/local/etc/redis/redis.conf"
    environment: 
      REDIS_REPLICATION_MODE: master
  
  cache-mru:
    container_name: cache-mru
    image: redis
    restart: always
    ports: 
      - "6380:6380"
    volumes:
      - "./data/redis-mru/redis-data:/var/lib/redis"
      - "./data/redis-mru/redis.conf:/usr/local/etc/redis/redis.conf"
    environment: 
      REDIS_REPLICATION_MODE: master